/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccounts"];
        put?: never;
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/api/accounts/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unarchiveAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCategories"];
        put?: never;
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unarchiveCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBuckets"];
        put?: never;
        post: operations["createBucket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveBucket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unarchiveBucket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTransactions"];
        put?: never;
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reverseTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parser-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listParserProfiles"];
        put?: never;
        post: operations["createParserProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadCSVStatement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listImportBatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getImportBatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/rows/{id}/categorization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["categorizeImportedRow"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/rows/{id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["skipImportedRow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/rows/{id}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["suggestImportedRowCategorization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCategorizationRules"];
        put?: never;
        post: operations["createCategorizationRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteCategorizationRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReconciliations"];
        put?: never;
        post: operations["createReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["discardDraftReconciliation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reopenReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/transactions.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            status: string;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            errors?: {
                [key: string]: string;
            };
        };
        CreateAccount: {
            name: string;
            /** @enum {string} */
            kind: "bank" | "cash" | "credit_card" | "loan" | "investment" | "other";
            /** @enum {string} */
            balanceClass: "asset" | "liability";
            /** @constant */
            currency: "INR";
            note?: string | null;
        };
        Account: components["schemas"]["CreateAccount"] & {
            /** Format: uuid */
            id: string;
            balance: components["schemas"]["MoneyAmount"];
            archived: boolean;
        };
        AccountList: {
            items: components["schemas"]["Account"][];
        };
        CreateCategory: {
            name: string;
            /** @enum {string} */
            kind: "income" | "expense";
            /** Format: uuid */
            parentId?: string | null;
        };
        CreateBucket: {
            name: string;
            note?: string | null;
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            kind: "income" | "expense";
            /** Format: uuid */
            parentId?: string | null;
            archived: boolean;
        };
        CategoryList: {
            items: components["schemas"]["Category"][];
        };
        Bucket: {
            /** Format: uuid */
            id: string;
            name: string;
            note?: string | null;
            balance: components["schemas"]["MoneyAmount"];
            archived: boolean;
            system: boolean;
        };
        BucketList: {
            items: components["schemas"]["Bucket"][];
        };
        /** @description Signed integer minor currency units encoded as a string; for INR the unit is paise */
        MoneyAmount: string;
        PostingInput: {
            /** Format: uuid */
            accountId: string;
            amount: components["schemas"]["MoneyAmount"];
            memo?: string | null;
        };
        BucketEntryInput: {
            /** Format: uuid */
            bucketId: string;
            /** Format: uuid */
            categoryId?: string | null;
            amount: components["schemas"]["MoneyAmount"];
            memo?: string | null;
        };
        CreateTransaction: {
            /** Format: date */
            occurredOn: string;
            description: string;
            /** @enum {string} */
            kind: "income" | "expense" | "transfer" | "refund" | "adjustment" | "opening_balance" | "bucket_transfer";
            postings?: components["schemas"]["PostingInput"][];
            bucketEntries?: components["schemas"]["BucketEntryInput"][];
        };
        Transaction: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            occurredOn: string;
            description: string;
            /** @enum {string} */
            kind: "income" | "expense" | "transfer" | "refund" | "adjustment" | "opening_balance" | "bucket_transfer";
            /** @enum {string} */
            status: "draft" | "posted" | "reversed";
            /** @enum {string} */
            origin: "manual" | "import" | "recurring_rule" | "system";
            /** Format: uuid */
            reversalOfId?: string | null;
            postings: components["schemas"]["Posting"][];
            bucketEntries: components["schemas"]["BucketEntry"][];
        };
        Posting: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            accountId: string;
            amount: components["schemas"]["MoneyAmount"];
            memo?: string | null;
        };
        BucketEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            bucketId: string;
            /** Format: uuid */
            categoryId?: string | null;
            amount: components["schemas"]["MoneyAmount"];
            memo?: string | null;
        };
        TransactionList: {
            items: components["schemas"]["Transaction"][];
            limit: number;
            offset: number;
        };
        Dashboard: {
            assets: components["schemas"]["MoneyAmount"];
            liabilities: components["schemas"]["MoneyAmount"];
            netCovered: components["schemas"]["MoneyAmount"];
            bucketTotal: components["schemas"]["MoneyAmount"];
            difference: components["schemas"]["MoneyAmount"];
            balanced: boolean;
            /** Format: int64 */
            importsNeedingReview: number;
        };
        Categorization: {
            bucketEntries?: components["schemas"]["BucketEntryInput"][];
        };
        CreateRule: {
            name: string;
            priority?: number;
            conditions: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            bucketId?: string | null;
            transactionKind?: string | null;
            autoApply?: boolean;
        };
        ParserProfile: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            format: "csv" | "xlsx" | "pdf";
            institution?: string | null;
            mapping: {
                [key: string]: unknown;
            };
            parserVersion: string;
        };
        ParserProfileList: {
            items: components["schemas"]["ParserProfile"][];
        };
        ImportUploadResult: {
            /** Format: uuid */
            id: string;
            status: string;
            imported: number;
            duplicates: number;
            invalid: number;
        };
        ImportBatchSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            accountId: string;
            fileName: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            imported: number;
            duplicates: number;
            invalid: number;
            pending: number;
        };
        ImportBatchList: {
            items: components["schemas"]["ImportBatchSummary"][];
            limit: number;
            offset: number;
        };
        ImportedRow: {
            /** Format: uuid */
            id: string;
            sourceRow: number;
            /** Format: date */
            transactionDate?: string | null;
            description?: string | null;
            reference?: string | null;
            amount?: components["schemas"]["MoneyAmount"] | null;
            balance?: components["schemas"]["MoneyAmount"] | null;
            /** Format: uuid */
            transactionId?: string | null;
            reviewStatus: string;
            parseErrors: string[];
        };
        ImportBatch: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            accountId: string;
            fileName: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            rows: components["schemas"]["ImportedRow"][];
        };
        ImportReviewResult: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            transactionId: string;
            /** @constant */
            reviewStatus: "reviewed";
        };
        Rule: {
            /** Format: uuid */
            id: string;
            name: string;
            priority: number;
            conditions: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            bucketId?: string | null;
            transactionKind?: string | null;
            autoApply: boolean;
            enabled: boolean;
        };
        RuleList: {
            items: components["schemas"]["Rule"][];
        };
        Suggestion: {
            /** Format: uuid */
            ruleId: string;
            ruleName: string;
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            bucketId?: string | null;
            transactionKind?: string | null;
            autoApply: boolean;
            confidence: string;
        };
        SuggestionList: {
            items: components["schemas"]["Suggestion"][];
        };
        CreateReconciliation: {
            /** Format: uuid */
            financialAccountId: string;
            /** Format: date */
            statementDate: string;
            statementBalance: components["schemas"]["MoneyAmount"];
            complete: boolean;
        };
        ReconciliationResult: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "in_progress" | "completed" | "reopened";
            computedBalance: components["schemas"]["MoneyAmount"];
            statementBalance: components["schemas"]["MoneyAmount"];
            difference: components["schemas"]["MoneyAmount"];
        };
        Reconciliation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            financialAccountId: string;
            /** Format: date */
            statementDate: string;
            statementBalance: components["schemas"]["MoneyAmount"];
            computedBalance: components["schemas"]["MoneyAmount"];
            difference: components["schemas"]["MoneyAmount"];
            /** @enum {string} */
            status: "in_progress" | "completed" | "reopened";
            /** Format: date-time */
            completedAt?: string | null;
        };
        ReconciliationList: {
            items: components["schemas"]["Reconciliation"][];
        };
    };
    responses: {
        /** @description Health status */
        Health: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Health"];
            };
        };
        /** @description Error response */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ID: string;
    };
    requestBodies: {
        CreateAccount: {
            content: {
                "application/json": components["schemas"]["CreateAccount"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Health"];
            default: components["responses"]["Problem"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Health"];
            503: components["responses"]["Problem"];
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateAccount"];
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    note?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    archiveAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    unarchiveAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unarchived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategory"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    archiveCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    unarchiveCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unarchived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listBuckets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Buckets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createBucket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBucket"];
            };
        };
        responses: {
            /** @description Bucket created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bucket"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    archiveBucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    unarchiveBucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unarchived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransaction"];
            };
        };
        responses: {
            /** @description Transaction created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    reverseTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    description?: string;
                };
            };
        };
        responses: {
            /** @description Reversal transaction created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listParserProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Parser profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParserProfileList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createParserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    format: "csv" | "xlsx" | "pdf";
                    institution?: string | null;
                    mapping: {
                        [key: string]: unknown;
                    };
                    parserVersion?: string;
                };
            };
        };
        responses: {
            /** @description Parser profile created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParserProfile"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    uploadCSVStatement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: uuid */
                    accountId: string;
                    /** @description JSON-encoded CSV mapping */
                    mapping?: string;
                    /**
                     * Format: uuid
                     * @description Existing CSV parser profile used when mapping is omitted
                     */
                    profileId?: string;
                    /** Format: binary */
                    file: string;
                } | unknown | unknown;
            };
        };
        responses: {
            /** @description Import created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportUploadResult"];
                };
            };
            409: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listImportBatches: {
        parameters: {
            query?: {
                status?: "uploaded" | "processing" | "ready" | "failed" | "completed";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import batches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getImportBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import batch */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatch"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    categorizeImportedRow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Categorization"];
            };
        };
        responses: {
            /** @description Row reviewed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReviewResult"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    skipImportedRow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skipped */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    suggestImportedRowCategorization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categorization suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listCategorizationRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categorization rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCategorizationRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRule"];
            };
        };
        responses: {
            /** @description Rule created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteCategorizationRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listReconciliations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reconciliations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReconciliation"];
            };
        };
        responses: {
            /** @description Reconciliation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationResult"];
                };
            };
            409: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    completeReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reconciliation completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationResult"];
                };
            };
            409: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    discardDraftReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft reconciliation discarded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    reopenReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reconciliation reopened */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationResult"];
                };
            };
            409: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    exportTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
