import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { http, HttpResponse } from "msw";
import { MemoryRouter, Route, Routes } from "react-router";
import { describe, expect, it } from "vitest";

import { server } from "../../test/server";
import { TransactionEditorPage } from "./transaction-editor-page";

describe("TransactionEditorPage", () => {
  it("posts the exact minor-unit command generated by an expense preset", async () => {
    let submitted: unknown;
    server.use(
      http.get("*/api/accounts", () => HttpResponse.json({ items: [
        { id: "account-1", name: "Daily bank", kind: "bank", balanceClass: "asset", currency: "INR", balance: "0", archived: false },
      ] })),
      http.get("*/api/buckets", () => HttpResponse.json({ items: [
        { id: "bucket-1", name: "Groceries", balance: "0", archived: false, system: false },
      ] })),
      http.get("*/api/categories", () => HttpResponse.json({ items: [
        { id: "category-1", name: "Food", kind: "expense", archived: false },
      ] })),
      http.post("*/api/transactions", async ({ request }) => {
        submitted = await request.json();
        return HttpResponse.json({
          id: "transaction-new",
          occurredOn: "2026-08-23",
          description: "Corner market",
          kind: "expense",
          status: "posted",
          origin: "manual",
          postings: [],
          bucketEntries: [],
        }, { status: 201 });
      }),
      http.get("*/api/dashboard", () => HttpResponse.json({})),
    );
    const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } });
    const user = userEvent.setup();

    render(
      <QueryClientProvider client={queryClient}>
        <MemoryRouter initialEntries={["/transactions/new"]}>
          <Routes>
            <Route path="/transactions/new" element={<TransactionEditorPage />} />
            <Route path="/transactions/:id" element={<p>Transaction created</p>} />
          </Routes>
        </MemoryRouter>
      </QueryClientProvider>,
    );

    await user.type(await screen.findByLabelText("Description"), "Corner market");
    await user.click(screen.getByRole("button", { name: "Post transaction" }));

    expect(await screen.findByText("Transaction created")).toBeInTheDocument();
    await waitFor(() => expect(submitted).toMatchObject({
      description: "Corner market",
      kind: "expense",
      postings: [{ accountId: "account-1", amount: "-10000" }],
      bucketEntries: [{ bucketId: "bucket-1", categoryId: "category-1", amount: "-10000" }],
    }));
  });
});
